var PAGE_TITLE = "noc_p5_gungfu-02_forces-01_friction";
/**jstephens 2016_04 - inspired by Nature of Code - shiffman**/
////////////
//SET GLOBALS
var INNER_WIDTH    = window.innerWidth;
var INNER_HEIGHT   = window.innerHeight;
var CANVAS;
var BGND_COLOR     = 127;


var TOTAL_VEHICLES = 10;
var vehicles       = [];

var surface;



function setup(){
  runBasicSetup(); 
  for (var i = 0; i < TOTAL_VEHICLES; i++){
    vehicles[i] = new Vehicle();
  }
  
  surface = new Surface();
}

function draw(){
  //establish drag and friction areas
  surface.display();
  
  //external forces acting upon the vehicle
  var windForce = createVector(0,0);
  
  for (var i = 0; i < vehicles.length; i++){
    //apply external forces
    vehicles[i].applyForce(windForce);
    
    //check if vehicle is on a surface or in a fluid
    if (surface.contains(vehicles[i])){
      surface.applyFrictionTo(vehicles[i]);
    }
    
    //apply internal forces
    vehicles[i].perlinSteer();        ////steering force generated by vehicle
    
    //apply net force and update 
    vehicles[i].update();
    vehicles[i].display();
    vehicles[i].checkBoundary();  
  }
}

function mousePressed(){
  
}


////////////////////////////////////////////////////
////SETUP and CONFIG
////////////////////////////////////////////////////
function runBasicSetup() {
  CANVAS = createCanvas(INNER_WIDTH, INNER_HEIGHT);
  CANVAS.position(0,0);
  smooth();
  displayPageTitle();
}

function displayPageTitle(){
  background(BGND_COLOR);      //clear CANVAS before draw
  //display PAGE_TITLE in CANVAS
  fill(255);
  textSize(18);
  text(PAGE_TITLE, width*.01, 40);
  
  textSize(14);
  var LESSON = "/*////Friction from Surface Object + Vehicle's PerlinSteerForce////\naccumulate forces\napply net acceleration*/";

  text(LESSON, width*.01, height*.6);
}
////END CONFIG
////////////////////////////////////////////////////






