var PAGE_TITLE = "noc_p5_gungfu-02_forces-02_02_history_lines";
/**jstephens 2016_04 - inspired by Nature of Code - shiffman**/
////////////
//SET GLOBALS
var INNER_WIDTH    = window.innerWidth;
var INNER_HEIGHT   = window.innerHeight;
var CANVAS;
var BGND_COLOR     = 0; // 127
var backgroundIsOn = true;


var TOTAL_VEHICLES = 5;
var vehicles       = [];

var surface;
var surfaceIsOn    = false;



function setup(){
  runBasicSetup(); 
  for (var i = 0; i < TOTAL_VEHICLES; i++){
    vehicles[i] = new Vehicle();
  }
  
  if (surfaceIsOn){
  surface = new Surface();
  }
}

function draw(){

  if (backgroundIsOn){
    displayPageTitle();
  } 
  
  //establish drag and friction areas
  //surface.display();
  //external forces acting upon the vehicle
  var windForce = createVector(0,0);
  
  for (var i = 0; i < vehicles.length; i++){
    //apply external forces
    vehicles[i].applyForce(windForce);
    
    
    //check if vehicle is on a surface or in a fluid
    if (surfaceIsOn){
      if (surface.contains(vehicles[i])){
        surface.applyFrictionTo(vehicles[i]);
      }
    }
    
    //apply internal forces
    vehicles[i].perlinSteer();        ////steering force generated by vehicle
    
    //apply net force and update 
    vehicles[i].update();
    vehicles[i].display();
    vehicles[i].checkBoundary();  
  }
}

function mousePressed(){
  
}


////////////////////////////////////////////////////
////SETUP and CONFIG
////////////////////////////////////////////////////
function runBasicSetup() {
  CANVAS = createCanvas(INNER_WIDTH, INNER_HEIGHT);
  CANVAS.position(0,0);
  smooth();
  displayPageTitle();
}

function displayPageTitle(){
  background(BGND_COLOR);      //clear CANVAS before draw
  //display PAGE_TITLE in CANVAS
  fill(255);
  /*
  textSize(18);
  text(PAGE_TITLE, width*.01, 40);
  
  textSize(14);
  var LESSON = "/*////Store and display vehicle location history////\nthis.history = [];\nthis.history.push(vehicle.location)\n*/";

  text(LESSON, width*.01, height*.6);
  */
}
////END CONFIG
////////////////////////////////////////////////////






